"use server";

import { revalidatePath } from "next/cache";

import { buildCertificateKey } from "@pioneers/core/files";
import { certificateMetadataSchema } from "@pioneers/core/schemas";
import { z } from "zod";

import { requireUser } from "@/lib/auth";
import { deleteObject } from "@/lib/r2";
import { getSupabaseServerClient } from "@/lib/supabase/server";

export type ActionResult<T = void> =
  { ok: true; data: T } | { ok: false; error: string; fieldErrors?: Record<string, string[]> };

const createCertificateSchema = certificateMetadataSchema.safeExtend({
  /** Generated by the client so the R2 key is known before the upload starts. */
  id: z.uuid(),
  clientId: z.uuid(),
  file_name: z.string().min(1).max(255),
  content_type: z.literal("application/pdf"),
  size_bytes: z.number().int().positive(),
});

/**
 * Create the certificate row *before* the file is uploaded.
 *
 * The row is what authorises the presigned PUT (see
 * /api/storage/upload-url): without it, any signed-in user could request a
 * write URL for an arbitrary key. The client deletes the row again if the
 * upload fails, so a failed upload leaves nothing behind.
 */
export async function createCertificate(input: unknown): Promise<ActionResult<{ id: string }>> {
  const profile = await requireUser();

  const parsed = createCertificateSchema.safeParse(input);
  if (!parsed.success) {
    return {
      ok: false,
      error: "Please correct the highlighted fields.",
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  const value = parsed.data;

  const r2Key = buildCertificateKey({
    certificateId: value.id,
    fileName: value.file_name,
    contentType: value.content_type,
  });

  const supabase = await getSupabaseServerClient();

  const { error } = await supabase.from("certificates").insert({
    id: value.id,
    client_id: value.clientId,
    title: value.title,
    file_name: value.file_name,
    r2_key: r2Key,
    content_type: value.content_type,
    size_bytes: value.size_bytes,
    company_name: value.company_name,
    certificate_number: value.certificate_number,
    issue_date: value.issue_date,
    expiry_date: value.expiry_date,
    job_id: value.job_id,
    uploaded_by: profile.id,
  });

  if (error) return { ok: false, error: error.message };

  revalidatePath("/dashboard/certificates");
  return { ok: true, data: { id: value.id } };
}

export async function updateCertificate(
  certificateId: string,
  input: unknown,
): Promise<ActionResult> {
  await requireUser();

  const parsed = certificateMetadataSchema.safeParse(input);
  if (!parsed.success) {
    return {
      ok: false,
      error: "Please correct the highlighted fields.",
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  const supabase = await getSupabaseServerClient();
  const { error } = await supabase
    .from("certificates")
    .update({
      title: parsed.data.title,
      company_name: parsed.data.company_name,
      certificate_number: parsed.data.certificate_number,
      issue_date: parsed.data.issue_date,
      expiry_date: parsed.data.expiry_date,
      job_id: parsed.data.job_id,
    })
    .eq("id", certificateId);

  if (error) return { ok: false, error: error.message };

  revalidatePath("/dashboard/certificates");
  return { ok: true, data: undefined };
}

/**
 * Soft-delete a certificate, then remove the object from R2.
 *
 * Order matters: the row goes first so the file stops being reachable even if
 * the R2 call fails. A leftover object is a storage-cost problem; a reachable
 * file for a "deleted" certificate is a disclosure problem.
 */
export async function deleteCertificate(certificateId: string): Promise<ActionResult> {
  await requireUser();

  const supabase = await getSupabaseServerClient();

  const { data: certificate } = await supabase
    .from("certificates")
    .select("r2_key")
    .eq("id", certificateId)
    .maybeSingle();

  const { error } = await supabase
    .from("certificates")
    .update({ deleted_at: new Date().toISOString() })
    .eq("id", certificateId);

  if (error) return { ok: false, error: error.message };

  if (certificate?.r2_key) {
    await deleteObject(certificate.r2_key).catch(() => {
      /* orphaned object; the row is already unreachable */
    });
  }

  revalidatePath("/dashboard/certificates");
  return { ok: true, data: undefined };
}

/** Hard-delete used to roll back a row whose upload failed. */
export async function discardFailedCertificate(certificateId: string): Promise<ActionResult> {
  await requireUser();

  const supabase = await getSupabaseServerClient();
  const { error } = await supabase.from("certificates").delete().eq("id", certificateId);

  if (error) return { ok: false, error: error.message };

  revalidatePath("/dashboard/certificates");
  return { ok: true, data: undefined };
}
