-- ============================================================================
-- pioneers-egy :: core schema
-- ============================================================================
-- Design notes
--   * Every user-generated row carries a `client_id` UUID generated by the
--     client. The mobile app is offline-first and replays queued mutations, so
--     inserts must be idempotent: `on conflict (client_id) do nothing`.
--   * `job_tasks.data` is JSONB. The six inspection subtypes have disjoint
--     field sets and more environmental forms are coming, so a shared Zod
--     discriminated union in @pioneers/core is the contract rather than six
--     near-empty tables. The one invariant SQL *can* express — that a subtype
--     belongs to its category — is enforced with a CHECK constraint below.
--   * Files live in Cloudflare R2, not Supabase Storage. We persist only the
--     object key; every read is a short-lived presigned GET minted server-side.
-- ============================================================================

create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_trgm with schema extensions;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type public.user_role as enum ('admin', 'manager', 'inspector');

create type public.job_status as enum ('draft', 'submitted');

create type public.task_category as enum ('inspection', 'environmental');

create type public.task_subtype as enum (
  -- inspection
  'lifting',
  'ndt',
  'testing',
  -- environmental (placeholders; real forms to be specified later)
  'env_option_1',
  'env_option_2',
  'env_option_3'
);

-- ---------------------------------------------------------------------------
-- updated_at trigger helper
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- profiles :: application-level mirror of auth.users
-- ---------------------------------------------------------------------------

create table public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  email       text not null,
  full_name   text not null default '',
  role        public.user_role not null default 'inspector',
  phone       text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.profiles is
  'One row per auth user. Populated by the on_auth_user_created trigger.';

create index profiles_role_idx on public.profiles (role);
create index profiles_email_idx on public.profiles (lower(email));

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- jobs :: one site visit for a project/company
-- ---------------------------------------------------------------------------

create table public.jobs (
  id            uuid primary key default gen_random_uuid(),
  client_id     uuid not null unique default gen_random_uuid(),
  project_name  text not null check (length(trim(project_name)) > 0),
  company_name  text not null check (length(trim(company_name)) > 0),
  visit_date    date not null,
  status        public.job_status not null default 'draft',
  notes         text,
  created_by    uuid not null references public.profiles (id) on delete restrict,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  submitted_at  timestamptz,
  deleted_at    timestamptz
);

comment on column public.jobs.client_id is
  'Client-generated idempotency key so the offline outbox can safely replay.';

create index jobs_created_by_idx on public.jobs (created_by);
create index jobs_status_idx on public.jobs (status);
create index jobs_visit_date_idx on public.jobs (visit_date desc);
create index jobs_active_idx on public.jobs (created_at desc) where deleted_at is null;
create index jobs_company_trgm_idx on public.jobs using gin (company_name extensions.gin_trgm_ops);
create index jobs_project_trgm_idx on public.jobs using gin (project_name extensions.gin_trgm_ops);

create trigger jobs_set_updated_at
  before update on public.jobs
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- job_tasks :: a job has many typed inspection tasks
-- ---------------------------------------------------------------------------

create table public.job_tasks (
  id          uuid primary key default gen_random_uuid(),
  client_id   uuid not null unique default gen_random_uuid(),
  job_id      uuid not null references public.jobs (id) on delete cascade,
  category    public.task_category not null,
  subtype     public.task_subtype not null,
  sort_order  integer not null default 0,
  data        jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  -- Keep the two dropdowns consistent: an "inspection" task can never carry an
  -- environmental subtype and vice versa.
  constraint job_tasks_subtype_matches_category check (
    (category = 'inspection'
      and subtype in ('lifting', 'ndt', 'testing'))
    or
    (category = 'environmental'
      and subtype in ('env_option_1', 'env_option_2', 'env_option_3'))
  )
);

comment on column public.job_tasks.data is
  'Subtype-specific fields. Validated by the shared Zod schema in @pioneers/core.';

create index job_tasks_job_id_idx on public.job_tasks (job_id, sort_order);
create index job_tasks_subtype_idx on public.job_tasks (subtype);

create trigger job_tasks_set_updated_at
  before update on public.job_tasks
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- task_photos :: R2 object references for a task
-- ---------------------------------------------------------------------------

create table public.task_photos (
  id            uuid primary key default gen_random_uuid(),
  client_id     uuid not null unique default gen_random_uuid(),
  task_id       uuid not null references public.job_tasks (id) on delete cascade,
  r2_key        text not null,
  file_name     text not null,
  content_type  text not null default 'image/jpeg',
  size_bytes    bigint not null default 0,
  width         integer,
  height        integer,
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now()
);

create index task_photos_task_id_idx on public.task_photos (task_id, sort_order);

-- ---------------------------------------------------------------------------
-- certificates :: uploaded PDFs, optionally linked to a job
-- ---------------------------------------------------------------------------

create table public.certificates (
  id                  uuid primary key default gen_random_uuid(),
  client_id           uuid not null unique default gen_random_uuid(),
  title               text not null check (length(trim(title)) > 0),
  file_name           text not null,
  r2_key              text not null,
  content_type        text not null default 'application/pdf',
  size_bytes          bigint not null default 0,
  company_name        text,
  certificate_number  text,
  issue_date          date,
  expiry_date         date,
  job_id              uuid references public.jobs (id) on delete set null,
  uploaded_by         uuid not null references public.profiles (id) on delete restrict,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  deleted_at          timestamptz,

  constraint certificates_dates_ordered check (
    expiry_date is null or issue_date is null or expiry_date >= issue_date
  )
);

create index certificates_job_id_idx on public.certificates (job_id);
create index certificates_uploaded_by_idx on public.certificates (uploaded_by);
create index certificates_active_idx on public.certificates (created_at desc) where deleted_at is null;
create index certificates_expiry_idx on public.certificates (expiry_date) where deleted_at is null;

-- Trigram indexes back the "search by file name" requirement with ILIKE '%...%'
create index certificates_title_trgm_idx on public.certificates using gin (title extensions.gin_trgm_ops);
create index certificates_file_name_trgm_idx on public.certificates using gin (file_name extensions.gin_trgm_ops);
create index certificates_company_trgm_idx on public.certificates using gin (company_name extensions.gin_trgm_ops);
create index certificates_number_trgm_idx on public.certificates using gin (certificate_number extensions.gin_trgm_ops);

create trigger certificates_set_updated_at
  before update on public.certificates
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- certificate_share_links :: the QR-code targets handed to external companies
-- ---------------------------------------------------------------------------

create table public.certificate_share_links (
  id                uuid primary key default gen_random_uuid(),
  certificate_id    uuid not null references public.certificates (id) on delete cascade,
  token             text not null unique check (length(token) >= 32),
  label             text,
  is_revoked        boolean not null default false,
  expires_at        timestamptz,
  view_count        integer not null default 0,
  download_count    integer not null default 0,
  created_by        uuid not null references public.profiles (id) on delete restrict,
  created_at        timestamptz not null default now(),
  last_accessed_at  timestamptz
);

comment on table public.certificate_share_links is
  'Tokens are high-entropy and deliberately unreadable by the anon key; the '
  'public /verify route resolves them with the service role so revocation and '
  'expiry are always honoured server-side.';

create index certificate_share_links_certificate_id_idx
  on public.certificate_share_links (certificate_id, created_at desc);

-- ---------------------------------------------------------------------------
-- certificate_access_log :: who opened/downloaded a shared certificate
-- ---------------------------------------------------------------------------

create table public.certificate_access_log (
  id             bigserial primary key,
  share_link_id  uuid not null references public.certificate_share_links (id) on delete cascade,
  action         text not null check (action in ('view', 'download')),
  user_agent     text,
  accessed_at    timestamptz not null default now()
);

create index certificate_access_log_link_idx
  on public.certificate_access_log (share_link_id, accessed_at desc);
